[package]
name = "genact"
description = "A nonsense activity generator"
version = "0.7.0"
repository = "https://github.com/svenstaro/genact"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["fake", "nonsense", "useless"]
categories = ["command-line-utilities", "command-line-interface"]
edition = "2018"

[dependencies]
pbr = "1.0"
yansi = "0.5"
rand = "0.7.0"
chrono = "0.4"
url = "2.1"
lazy_static = "1.4"
humantime = "1.3"
regex = "1.3"
fake = "1.3.0"

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
clap = "2.33"
ctrlc = "3.1"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = "0.3"
stdweb = "0.4"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
